version: 0.0
os: linux

files:
  - source: frontend/
    destination: /home/ubuntu/sas/frontend
  - source: backend/backend.jar
    destination: /home/ubuntu/sas/backend

hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
