version: '3'
services: 
  frontend:
    image: devsunriver/sas_client:test
    container_name: frontend
    ports:
      - "3000:3000"

  backend:
    image: devsunriver/sas_server:test
    container_name: backend
    ports: 
      - "8080:8080"

  redis: 
    image: redis:alpine
    container_name: redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6379:6379"