services: 
  frontend:
    build: ./client
    container_name: frontend
    environment:
      - REACT_APP_API_TARGET=http://backend:8080
    ports:
      - "3000:3000"

  backend:
    build: ./server
    container_name: backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal/crud?serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=k10241024!
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_CACHE_type=redis
      - SPRING_DATA_REDIS_REPOSITORIES_ENABLED=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    ports: 
      - "8080:8080"
    depends_on:
      - redis
    command: ["sh", "-c", "dockerize -wait tcp://host.docker.internal:3306 -wait tcp://redis:6379 -timeout 30s && java -jar app.jar"]

  redis: 
    image: redis:7.4.0-alpine
    container_name: redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge
