services: 
  frontend:
    build: ./client
    container_name: frontend
    environment:
      - REACT_APP_API_TARGET=http://backend:8080
      - REACT_APP_WS_TARGET=http://localhost:8080
    ports:
      - "3000:3000"

  backend:
    build: ./server
    container_name: backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/slime
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_CACHE_type=redis
      - SPRING_DATA_REDIS_REPOSITORIES_ENABLED=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SERVER_ACCOUNT_ADMIN_ID=admin
      - SERVER_ACCOUNT_ADMIN_PWD=1234
    ports: 
      - "8080:8080"
    depends_on:
      - redis
    command: ["sh", "-c", "dockerize -wait tcp://mysql:3306 -wait tcp://redis:6379 -timeout 30s && java -jar app.jar"]

  redis: 
    image: redis:7.4.0-alpine
    container_name: redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: slime
      MYSQL_USER: test
      MYSQL_PASSWORD: test

