FROM maven:3.9.8-eclipse-temurin-21-alpine AS build

RUN ["mkdir","-p","app"]

COPY pom.xml /app/pom.xml
COPY src /app/src

WORKDIR /app

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21

WORKDIR /app

ARG JAR_FILE=*.jar

COPY --from=build /app/target/${JAR_FILE} ./app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]


