FROM maven:3.9.8-eclipse-temurin-21-alpine AS build

RUN ["mkdir","-p","app"]

COPY pom.xml /app/pom.xml
COPY src /app/src

WORKDIR /app

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21

WORKDIR /app

# Download and install dockerize
RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://github.com/jwilder/dockerize/releases/download/v0.7.0/dockerize-alpine-linux-amd64-v0.7.0.tar.gz \
    | tar xzf - -C /usr/local/bin && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ARG JAR_FILE=*.jar

COPY --from=build /app/target/${JAR_FILE} ./app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]