name: Deploy 

on:
  push:
    branches:
      - main  

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'

    - name: Install dependencies
      run: |
        cd client
        npm install

    - name: Build project
      run: |
        cd client
        npm run build

    - name: Upload to S3
      run: |
        aws s3 sync client/build s3://${{ secrets.AWS_S3_BUCKET }}/frontend --delete 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-northeast-2

  build-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Install server dependencies and build
      run: |
        cd server
        mvn clean package

    - name: Upload to S3
      run: |
        aws s3 sync server/target s3://${{ secrets.AWS_S3_BUCKET }}/backend --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-northeast-2

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to CodeDeploy
        uses: aws-actions/aws-cli-action@v1
        with:
          args: deploy create-deployment --application-name sas-code-deploy --deployment-group-name sas --s3-location bucket=sas-deploy-bucket,key=cd.zip,bundleType=zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:  ap-northeast-2
